api/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^documents/$', views.NsDocumentListReadOnlyView.as_view(), name='documents'),
    url(r'^documents/revisions/$', views.NsDocumentRevisionReadOnlyListView.as_view(), name='revisions'),
    url(r'^documents/types/$', views.NsDocumentTypeListCreateView.as_view(), name='document_types'),
    url(r'^documents/formats/$', views.NsDocumentFormatListCreateView.as_view(), name='document_formats'),
    url(r'^projects/$', views.NsProjectListCreateView.as_view(), name='projects'),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

documents/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout_then_login, login
from django.views.generic.base import TemplateView

from . import views

urlpatterns = [
    url(r'^login', login, name='login'),
    url(r'^logout', logout_then_login, name='logout'),
    url(r'^partials/documents/table', views.DocumentTableView.as_view(), name='table'),
    url(r'^partials/documents/form', views.DocumentFormView.as_view(), name='form'),
    url(r'^', TemplateView.as_view(template_name="documents/documents.html"), name='home'),
]

nsdocuments/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import api.views
from . import views

urlpatterns = [
    url(r'api/v1/', include('api.urls', namespace='api')),
    url(r'^$', views.NsDocumentsRedirectView.as_view(), name='redirect'),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'nsdocuments/', include('documents.urls', namespace='documents'))
]

documents/models.py
from django.db import models
from django.contrib.auth.models import User
from django_extensions.db.models import TimeStampedModel
import datetime


class NsDocument(TimeStampedModel):
    def __str__(self):
        return str(self.revisions.order_by('-id').first())


class NsDocumentRevision(TimeStampedModel):
    CONCISE_DESCRIPTION_MAX_LENGTH = 32
    DOCUMENT_REVISION_LENGTH = 3
    DOCUMENT_NUMBER_BASE = 1000000
    DEFAULT_FILE_PATH = '//Nucleus-NAS1/Nucleus/PROJECTS/'

    document = models.ForeignKey('NsDocument', related_name='revisions')
    revision = models.PositiveIntegerField(default=0)
    created_by = models.ForeignKey(User)

    project = models.ForeignKey('NsProject')
    document_type = models.ForeignKey('NsDocumentType')
    concise_description = models.CharField(max_length=64)
    verbose_description = models.TextField(blank=True, default="")
    document_format = models.ForeignKey('NsDocumentFormat')
    filename = models.CharField(max_length=255, blank=True, unique=True)
    filepath = models.FilePathField(match='//Nucleus-NAS1/Nucleus/PROJECTS/*', unique=True)

    def format_document_number(self):
        document_number = str(self.document.id + self.DOCUMENT_NUMBER_BASE)
        return document_number

    def format_revision_number(self):
        try:
            revision_number = str(self.revision)
            padding_length = self.DOCUMENT_REVISION_LENGTH - len(revision_number)
            if padding_length > 0:
                padding = '0' * padding_length
                revision_number = padding + revision_number
        except Exception as e:
            revision_number = '0'
        return revision_number

    def format_concise_description(self):
        concise_description = self.concise_description.title()
        concise_description = ''.join(
            e for e in concise_description if e.isalnum()
        )
        if len(concise_description) > self.CONCISE_DESCRIPTION_MAX_LENGTH:
            concise_description = concise_description[:self.CONCISE_DESCRIPTION_MAX_LENGTH]
        return concise_description

    def __str__(self):
        project_code = str(self.project.format_code())

        document_type_code = str(self.document_type.format_code())

        document_number = self.format_document_number()

        date = datetime.datetime.now().strftime("%Y%m%d")

        revision = self.format_revision_number()

        concise_description = self.format_concise_description()

        file_ext = self.document_format.file_extension

        return project_code + "_" + \
               document_type_code + "_" + \
               document_number + "_" + \
               date + "_" + "V" + \
               revision + "_" + \
               concise_description + \
               '.' + file_ext

    def save(self, **kwargs):
        self.filename = self.__str__()
        self.filepath = self.DEFAULT_FILE_PATH + self.filename
        super().save(**kwargs)

    class Meta:
        unique_together = ('document', 'revision')


class NsDocumentOldRevision(TimeStampedModel):
    document = models.ForeignKey('NsDocument', related_name='old_revisions')
    revision = models.PositiveIntegerField()
    created_by = models.ForeignKey(User)

    project = models.ForeignKey('NsProject')
    document_type = models.ForeignKey('NsDocumentType')
    concise_description = models.CharField(max_length=64)
    verbose_description = models.TextField(blank=True, default="")
    document_format = models.ForeignKey('NsDocumentFormat')
    filename = models.CharField(max_length=255, blank=True, unique=True)
    filepath = models.FilePathField(match='//Nucleus-NAS1/Nucleus/PROJECTS/*', unique=True)

    def __str__(self):
        return self.filename

    class Meta:
        unique_together = ('document', 'revision')


class NsDocumentType(TimeStampedModel):
    DOCUMENT_TYPE_LENGTH = 3
    name = models.CharField(max_length=63, unique=True)
    code = models.CharField(max_length=3, unique=True)

    def format_code(self):
        document_code = str(self.code)
        padding_length = self.DOCUMENT_TYPE_LENGTH - len(document_code)
        if padding_length > 0:
            padding = '0' * padding_length
            document_code = padding + document_code
        return document_code

    def __str__(self):
        return self.name + '_' + self.format_code()


class NsDocumentFormat(TimeStampedModel):
    name = models.CharField(max_length=32, unique=True)
    file_extension = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name + '_' + self.file_extension


class NsProject(TimeStampedModel):
    PROJECT_CODE_LENGTH = 5
    name = models.CharField(max_length=64, unique=True)

    def format_code(self):
        project_code = str(self.id)
        padding_length = self.PROJECT_CODE_LENGTH - len(project_code)
        if padding_length > 0:
            padding = '0' * padding_length
            project_code = padding + project_code
        return project_code

    def __str__(self):
        return self.name + '_' + self.format_code()

documents/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from documents.models import NsDocumentRevision


class NsDocumentRevisionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(NsDocumentRevisionForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-documentForm'
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('save', 'save'))

    class Meta:
        model = NsDocumentRevision
        fields = ('project', 'document_type',
                  'concise_description', 'verbose_description',
                  'document_format')

documents/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.views.generic.edit import FormView

from documents.forms import NsDocumentRevisionForm


class DocumentTableView(LoginRequiredMixin, TemplateView):
    template_name = 'documents/angularjs/partials/documentsTableNgTable.html'


class DocumentFormView(LoginRequiredMixin, TemplateView):
    template_name = 'documents/angularjs/partials/documentForm.html'


class DocumentFormCrispyView(FormView):
    template_name = 'documents/angularjs/partials/documentForm.html'
    form_class = NsDocumentRevisionForm
    success_url = 'nsdocuments:table'

    def form_valid(self, form):
        return super(DocumentFormCrispyView, self).form_invalid(form)

documents/templates/documents/base_bootstrap.html
{% load staticfiles %}

<html>
<head>
    {% block stylesheets %}
        <link href="{% static 'nsdocuments/bower_components/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'nsdocuments/bower_components/bootstrap/dist/css/bootstrap-theme.css' %}" rel="stylesheet" type="text/css">
    {% endblock stylesheets %}
</head>

<div class="content">
    {% block content %}
    {% endblock content %}
</div>

{% block javascripts %}
    <script src="{% static "nsdocuments/bower_components/jquery/dist/jquery.js" %}"></script>
    <script src="{% static "nsdocuments/bower_components/bootstrap/dist/js/bootstrap.js" %}"></script>
    <script src="{% static "nsdocuments/bower_components/format/format.js" %}"></script>
{% endblock javascripts %}
</html>

documents/templates/documents/documents.html
{% load staticfiles %}
{% load djng_tags %}
<!DOCTYPE html>
<html ng-app="app"
      style="height: 100%; width: 100%; position: fixed; top: 0; bottom: 0; left: 0;">

<head>
    <meta charset="UTF-8">
    <title>NS Docs</title>

    <link href="{% static 'nsdocuments/bower_components/angular-ui-layout/src/ui-layout.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'nsdocuments/bower_components/bootstrap/dist/css/bootstrap.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'nsdocuments/bower_components/bootstrap/dist/css/bootstrap-theme.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'nsdocuments/bower_components/angular-ui-grid/ui-grid.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'nsdocuments/node_modules/ng-table/bundles/ng-table.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'nsdocuments/css/font-awesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'djng/css/styles.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'djng/css/bootstrap3.css' %}" rel="stylesheet" type="text/css">

    <style>
        img {
            height: 35px;
        }

        .ns-background {
            height: 100%;
            width: 100%;
        }

        .eighties-purple {
            background: #41295a; /* fallback for old browsers */
            background: -webkit-linear-gradient(to left, #41295a, #2F0743); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to left, #41295a, #2F0743); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        .shallow-space {
            background: #232526; /* fallback for old browsers */
            background: -webkit-linear-gradient(to left, #232526, #414345); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to left, #232526, #414345); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        .deep-space {
            background: #000000; /* fallback for old browsers */
            background: -webkit-linear-gradient(to left, #000000, #434343); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to left, #000000, #434343); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }

        .ns-table {
            background-color: transparent;
        }

        .ns-header {
            color: grey;
        }

        td {
            text-align: center;
        }

    </style>

</head>

<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <div class="navbar-header">
            <a ui-sref="app.documentList" class="navbar-brand">
                <img src="{% static 'nsdocuments/img/ns-icon.png' %}"/>
            </a>
        </div>

        <div class="collapse navbar-collapse" id="home-navbar-collapse">

            <ul class="nav navbar-nav">
                <li>
                    <a ui-sref="app.documentList" class="btn btn-default navbar-btn">Home</a>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'admin:login' %}" class="btn btn-default navbar-btn">Admin</a>
                </li>
                <li>
                    <a href="{% url 'documents:logout' %}" class="btn btn-default navbar-btn">Logout</a>
                </li>
            </ul>

        </div>

    </div>
</nav>

<h2 class="page-header ns-header">
    NS Documents
</h2>


{% angularjs %}

    <div style="overflow: auto;">
        <ui-view></ui-view>
    </div>

{% endangularjs %}


<script src="{% static 'nsdocuments/bower_components/jquery/dist/jquery.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/lodash/dist/lodash.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular/angular.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-touch/angular-touch.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-animate/angular-animate.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-spinner/dist/angular-spinner.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/spin/javascripts/jquery.spin.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-ui-grid/ui-grid.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-resource/angular-resource.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/moment/moment.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-sanitize/angular-sanitize.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-bootstrap/ui-bootstrap-tpls.js' %}"></script>
<script src="{% static 'djng/js/django-angular.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/bootstrap/dist/js/bootstrap.js' %}"
        type="text/javascript"></script>
<script src="{% static 'nsdocuments/bower_components/randomcolor/randomColor.js' %}" type="text/javascript"></script>
<script src="{% static 'nsdocuments/bower_components/angular-translate/angular-translate.js' %}"></script>
<script src="{% static 'nsdocuments/angular-ui-router/release/angular-ui-router.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-websocket/dist/angular-websocket.js' %}"
        type="text/javascript"></script>
<script src="{% static 'nsdocuments/bower_components/angular-websocket/dist/angular-websocket-mock.js' %}"
        type="text/javascript"></script>
<script src="{% static 'nsdocuments/bower_components/angular-ui-layout/src/ui-layout.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/api-check/dist/api-check.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-formly/dist/formly.js' %}"></script>
<script src="{% static 'nsdocuments/bower_components/angular-formly-templates-bootstrap/dist/angular-formly-templates-bootstrap.js' %}"></script>
<script src="{% static 'nsdocuments/node_modules/ng-table/bundles/ng-table.js' %}"></script>

<script>
    angular.module("app",
        ["ngResource", "ngWebSocket", "djng.forms", "ui.bootstrap",
            "ngAnimate", "djng.urls", "ngSanitize", "formly", "ngTable",
            "formlyBootstrap", "angularSpinner", "ui.router",
            "app.forms", "app.tables", "app.services", "app.filters"])
        .config(function ($locationProvider, $httpProvider) {

            $httpProvider.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
            $httpProvider.defaults.headers.common['X-CSRFToken'] = '{{ csrf_token }}';

        })
        .config(function ($resourceProvider) {
            $resourceProvider.defaults.stripTrailingSlashes = false;
        })
        .config(function ($stateProvider, $urlRouterProvider) {
            $urlRouterProvider.otherwise("list");

            $stateProvider
                .state("app", {
                    url: "/",
                    template: '<div ui-view></div>',
                    resolve: {
                        projects: function (NsProjectService) {
                            return NsProjectService.resolver();
                        }
                    }
                })
                .state("app.documentList", {
                    url: "list",
                    component: 'documentTable',
                    bindings: {documents: 'documents'}
                })
                .state("app.documentCreate", {
                    url: "create",
                    component: "documentForm",
                })
                .state("app.documentRevise", {
                    url: "revise/:documentId",
                    component: "documentForm",
                })
        })
        .constant("websocketUrl", "{{ WEBSOCKET_URL }}")
        .constant("username", "request.user.username")
</script>

<script src="{% static 'nsdocuments/bower_components/angular-spinner/dist/angular-spinner.js' %}"></script>
<script src="{% static 'documents/angularjs/components/nsdocumentTableNgTable.js' %}"></script>
<script src="{% static 'documents/angularjs/components/nsdocumentForm.js' %}"></script>
<script src="{% static 'documents/angularjs/components/nsdocumentServices.js' %}"></script>
<script src="{% static 'documents/angularjs/components/nsdocumentFilters.js' %}"></script>

</body>

</html>